// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// compute_cost_matrix_cpp
NumericMatrix compute_cost_matrix_cpp(List sn_x, List sn_y, NumericVector penalty);
RcppExport SEXP _fastKar_compute_cost_matrix_cpp(SEXP sn_xSEXP, SEXP sn_ySEXP, SEXP penaltySEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List >::type sn_x(sn_xSEXP);
    Rcpp::traits::input_parameter< List >::type sn_y(sn_ySEXP);
    Rcpp::traits::input_parameter< NumericVector >::type penalty(penaltySEXP);
    rcpp_result_gen = Rcpp::wrap(compute_cost_matrix_cpp(sn_x, sn_y, penalty));
    return rcpp_result_gen;
END_RCPP
}
// hash_karyotype_cpp
std::string hash_karyotype_cpp(List snode_id, LogicalVector circular);
RcppExport SEXP _fastKar_hash_karyotype_cpp(SEXP snode_idSEXP, SEXP circularSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List >::type snode_id(snode_idSEXP);
    Rcpp::traits::input_parameter< LogicalVector >::type circular(circularSEXP);
    rcpp_result_gen = Rcpp::wrap(hash_karyotype_cpp(snode_id, circular));
    return rcpp_result_gen;
END_RCPP
}
// traverse_graph_cpp
List traverse_graph_cpp(DataFrame A, NumericVector loose_ends);
RcppExport SEXP _fastKar_traverse_graph_cpp(SEXP ASEXP, SEXP loose_endsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< DataFrame >::type A(ASEXP);
    Rcpp::traits::input_parameter< NumericVector >::type loose_ends(loose_endsSEXP);
    rcpp_result_gen = Rcpp::wrap(traverse_graph_cpp(A, loose_ends));
    return rcpp_result_gen;
END_RCPP
}
// traverse_graph_v2_cpp
List traverse_graph_v2_cpp(DataFrame A, NumericVector loose_ends);
RcppExport SEXP _fastKar_traverse_graph_v2_cpp(SEXP ASEXP, SEXP loose_endsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< DataFrame >::type A(ASEXP);
    Rcpp::traits::input_parameter< NumericVector >::type loose_ends(loose_endsSEXP);
    rcpp_result_gen = Rcpp::wrap(traverse_graph_v2_cpp(A, loose_ends));
    return rcpp_result_gen;
END_RCPP
}
// traverse_graph_v2_batch_cpp
List traverse_graph_v2_batch_cpp(DataFrame A, List perms, NumericVector loose_ends);
RcppExport SEXP _fastKar_traverse_graph_v2_batch_cpp(SEXP ASEXP, SEXP permsSEXP, SEXP loose_endsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< DataFrame >::type A(ASEXP);
    Rcpp::traits::input_parameter< List >::type perms(permsSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type loose_ends(loose_endsSEXP);
    rcpp_result_gen = Rcpp::wrap(traverse_graph_v2_batch_cpp(A, perms, loose_ends));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_fastKar_compute_cost_matrix_cpp", (DL_FUNC) &_fastKar_compute_cost_matrix_cpp, 3},
    {"_fastKar_hash_karyotype_cpp", (DL_FUNC) &_fastKar_hash_karyotype_cpp, 2},
    {"_fastKar_traverse_graph_cpp", (DL_FUNC) &_fastKar_traverse_graph_cpp, 2},
    {"_fastKar_traverse_graph_v2_cpp", (DL_FUNC) &_fastKar_traverse_graph_v2_cpp, 2},
    {"_fastKar_traverse_graph_v2_batch_cpp", (DL_FUNC) &_fastKar_traverse_graph_v2_batch_cpp, 3},
    {NULL, NULL, 0}
};

RcppExport void R_init_fastKar(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
