# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

compute_cost_matrix_cpp <- function(sn_x, sn_y, penalty) {
    .Call(`_fastKar_compute_cost_matrix_cpp`, sn_x, sn_y, penalty)
}

traverse_graph_cpp <- function(A, loose_ends) {
    .Call(`_fastKar_traverse_graph_cpp`, A, loose_ends)
}

